import { EFFORTS } from '../../hooks/lib/types.ts';
import { LANGS, t } from './i18n/index.ts';

export type FieldKind = 'bool' | 'number' | 'text' | 'effort' | 'select' | 'list' | 'lines';

export type FieldDef = {
  /** Dotted path into GovernorConfig, e.g. `router.upgradeAt`. */
  path: string;
  label: string;
  help: string;
  kind: FieldKind;
  step?: number;
  min?: number;
  max?: number;
  unit?: string;
  options?: { value: string; label: string }[];
  disabled?: boolean;
  placeholder?: string;
  mono?: boolean;
};

export type Section = { id: string; title: string; intro?: string; fields: FieldDef[] };

export const effortOptions = EFFORTS.map((e) => ({ value: e, label: e }));

const prob = { kind: 'number', step: 0.05, min: 0, max: 1 } as const;

/** The sections, built on every call so the texts follow the current language. */
export function getSections(): Section[] {
  return [
    {
      id: 'general',
      title: t('General'),
      fields: [
        {
          path: 'enabled',
          label: t('Mod enabled'),
          kind: 'bool',
          help: t('Main switch. When off, the mod changes nothing in Claude Code: no model, no effort, no subagents, no compaction. The same switch is the “On” badge at the top of the page.'),
        },
        {
          path: 'mode',
          label: t('Mode'),
          kind: 'select',
          options: [
            { value: 'active', label: t('Active') },
            { value: 'shadow', label: t('Shadow mode (only records decisions)') },
          ],
          help: t('In shadow mode Jev still makes decisions and writes them to the journal, but changes nothing in Claude Code. This lets you evaluate the mod before turning it on: compare “what would have happened” with what you choose yourself. Jev requests cost the same as usual.'),
        },
        {
          path: 'shadowPaths',
          label: t('Shadow mode paths'),
          kind: 'lines',
          placeholder: '~/Documents/my-project',
          help: t('One path per line (~ is allowed). Sessions whose working folder starts with such a path run in shadow mode; the rest follow “Mode”. Handy for trying the mod on one project without touching the others.'),
        },
        {
          path: 'activePaths',
          label: t('Paths where the mod is always active'),
          kind: 'lines',
          placeholder: '~/Documents/my-project',
          help: t('One path per line. Here the mod controls models even in shadow mode, and these paths take precedence over the list above. For example, shadow mode everywhere except the one project where you are testing the mod.'),
        },
        {
          path: 'excludeProjects',
          label: t('Projects without Jev'),
          kind: 'lines',
          placeholder: '~/work/client-repo',
          help: t('One path per line. In these projects the mod sends nothing to Jev (OpenRouter): no model and effort choice, no compaction or trimming through Jev, no turn selection for the capsule. For third-party or work code. In other projects secrets (keys, tokens, passwords) are replaced with [secret] before sending anyway, but code and paths go out as they are.'),
        },
        {
          path: 'codex.enabled',
          label: 'Codex',
          kind: 'bool',
          disabled: true,
          help: t('Codex is coming in the next version.'),
        },
      ],
    },
    {
      id: 'models',
      title: t('Models'),
      intro: t('The mod chooses between two tiers. Change the identifiers only when new versions are released.'),
      fields: [
        {
          path: 'models.standard',
          label: t('Standard tier (Sonnet)'),
          kind: 'text',
          mono: true,
          help: t('Model for tasks where Sonnet 5.5 is enough. Uses up subscription limits noticeably slower than Opus.'),
        },
        {
          path: 'models.strong',
          label: t('Strong tier (Opus)'),
          kind: 'text',
          mono: true,
          help: t('Model for hard and risky tasks. Higher quality, limits are used up faster.'),
        },
        {
          path: 'models.light',
          label: t('Light model (Haiku)'),
          kind: 'text',
          mono: true,
          help: t('Model for read-only subagents with an easy task, when “Light model for reading subagents” is on. It has no effort setting.'),
        },
      ],
    },
    {
      id: 'main',
      title: t('Main chat'),
      intro:
        t('Thresholds are probabilities from Jev (0–1). Switching the model in the middle of a long chat resets the prompt cache and is expensive, so the mod switches freely only where the cache is cold or the context is small.'),
      fields: [
        {
          path: 'router.mainModel',
          label: t('Choose the main chat model'),
          kind: 'bool',
          help: t('Jev decides on every turn whether to use Sonnet or Opus. When off, the model stays the one you chose yourself.'),
        },
        {
          path: 'router.mainEffort',
          label: t('Choose effort every turn'),
          kind: 'bool',
          help: t('Jev picks the reasoning depth for each turn. Changing effort does not reset the cache on Opus/Sonnet 5.5, so it is safe. When off, effort stays as it was.'),
        },
        {
          path: 'router.upgradeAt',
          label: t('Threshold for switching to Opus'),
          ...prob,
          help: t('The probability from Jev that Opus is needed at which the main chat switches to Opus where the cache is cold or the context is small. A lower threshold means Opus more often (higher quality, limits spent faster); a higher one, less often.'),
        },
        {
          path: 'router.forceUpgradeAt',
          label: t('Threshold for forced switch to Opus'),
          ...prob,
          help: t('The probability that Opus is needed at which the chat switches even with a warm cache. This is expensive: the whole context is read again. A higher threshold means the mod breaks the cache less often, but stays on Sonnet longer where Opus is needed.'),
        },
        {
          path: 'router.downgradeAt',
          label: t('Threshold for returning to Sonnet'),
          ...prob,
          help: t('The probability that Sonnet is enough at which the chat returns from Opus to Sonnet (where that is cheap). A higher threshold is more cautious: you stay on Opus longer and spend more.'),
        },
        {
          path: 'router.cheapSwitchTokens',
          label: t('Cheap switch: context up to'),
          kind: 'number',
          step: 1000,
          min: 0,
          max: 2_000_000,
          unit: t('tokens'),
          help: t('If the context is no larger than this, switching to Opus counts as cheap: there is almost nothing to lose in the cache. Switching to Sonnet is decided in dollars (setting below).'),
        },
        {
          path: 'router.expectedTurns',
          label: t('Switch to Sonnet pays off within, turns'),
          kind: 'number',
          step: 1,
          min: 1,
          max: 100,
          unit: t('turns'),
          help: t('Switching the main chat to Sonnet costs writing the whole context into the cache of the new model; the benefit is cheaper output and writing of new content on every following turn (cache reads cost the same on Opus and Sonnet). The mod switches only if the benefit over this many turns exceeds the cost of switching. Both amounts are visible in the journal, in the decision reasons.'),
        },
        {
          path: 'router.standardMaxContextTokens',
          label: t('Maximum context for Sonnet'),
          kind: 'number',
          step: 10_000,
          min: 10_000,
          max: 2_000_000,
          unit: t('tokens'),
          help: t('If the context is larger, the chat is not moved to Sonnet: on a long context Opus is more reliable, and switching models is expensive.'),
        },
        {
          path: 'router.cacheTtlMinutes',
          label: t('Cache lifetime'),
          kind: 'number',
          step: 1,
          min: 1,
          max: 1440,
          unit: t('min'),
          help: t('After this many idle minutes the prompt cache counts as cold, and switching models costs nothing. Do not set it higher than the real cache lifetime of your subscription: the mod would treat the cache as warm when it has already gone cold, or the other way round.'),
        },
        {
          path: 'router.minEffort',
          label: t('Minimum effort'),
          kind: 'effort',
          help: t('The mod never lowers effort below this level. A higher minimum means steadier quality but smaller savings.'),
        },
        {
          path: 'router.maxEffort',
          label: t('Maximum effort'),
          kind: 'effort',
          help: t('The mod never raises effort above this level. max and xhigh use up limits heavily; it cannot be lower than the minimum.'),
        },
        {
          path: 'router.defaultEffort',
          label: t('Default effort'),
          kind: 'effort',
          help: t('Used when Jev is not sure about its estimate.'),
        },
        {
          path: 'router.fallbackEffort',
          label: t('Effort when Jev does not respond'),
          kind: 'effort',
          help: t('The first turn of a chat or subagent when Jev is unavailable and there is no previous decision. Without this, the turn would run at the session effort (often xhigh).'),
        },
        {
          path: 'router.effortConfidenceAt',
          label: t('Confidence threshold for effort'),
          ...prob,
          help: t('If the confidence of Jev in the effort estimate is below this threshold, the estimate is ignored and the default effort is used.'),
        },
        {
          path: 'router.escalateAfterErrors',
          label: t('Raise effort after errors'),
          kind: 'number',
          step: 1,
          min: 0,
          max: 20,
          unit: t('errors per turn'),
          help: t('How many failed tool calls in one turn raise effort by one level. 0 means never.'),
        },
        {
          path: 'router.riskyAt',
          label: t('Threshold for a “risky” task'),
          ...prob,
          help: t('The probability that the task is risky (irreversible actions, production) at which effort is raised to at least high and Opus is used. A lower threshold means more caution and more spending.'),
        },
        {
          path: 'router.continuationAt',
          label: t('Threshold for “continuation”'),
          ...prob,
          help: t('The probability that the message continues the previous task; then the decision of the previous turn is repeated. A lower threshold means fewer needless switches, but the previous model may be kept longer.'),
        },
        {
          path: 'router.budgetAware',
          label: t('Take subscription limits into account'),
          kind: 'bool',
          help: t('When the limit windows (5 hours and a week) are being used up faster than the usual pace, the mod saves: it takes Opus and high effort less often. When off, decisions do not depend on the remaining limits.'),
        },
      ],
    },
    {
      id: 'subagents',
      title: t('Subagents'),
      fields: [
        {
          path: 'router.subagents',
          label: t('Choose subagent model and effort'),
          kind: 'bool',
          help: t('Jev decides when each subagent is launched. A subagent has its own context, so the main chat cache does not suffer.'),
        },
        {
          path: 'router.subagentStrongAt',
          label: t('Opus threshold for a subagent'),
          ...prob,
          help: t('The probability that Opus is needed at which a subagent is launched on Opus. A lower threshold means more subagents on Opus (higher quality, more spending).'),
        },
        {
          path: 'router.lightSubagents',
          label: t('Light model for reading subagents'),
          kind: 'select',
          options: [
            { value: 'shadow', label: t('Shadow (only record what it would choose)') },
            { value: 'on', label: t('On') },
            { value: 'off', label: t('Off') },
          ],
          help: t('Read-only subagents with an easy task (search, listing, reading files) can run on Haiku: its cache reads cost half as much, and reading is where subagents spend. It never applies to subagents that can edit, to risky tasks, or to ones that need reasoning. If the task grows (many steps) or tools keep failing, the subagent moves to the standard model.'),
        },
        {
          path: 'router.lightBelow',
          label: t('Light model: Opus probability below'),
          ...prob,
          help: t('A subagent goes to the light model only when the probability that it needs Opus is below this.'),
        },
        {
          path: 'router.lightMaxSteps',
          label: t('Light model: steps before moving up'),
          kind: 'number',
          step: 5,
          min: 1,
          max: 500,
          help: t('The light model has a smaller context window. After this many steps the subagent moves to the standard model.'),
        },
      ],
    },
    {
      id: 'agents',
      title: t('Specialist agents'),
      intro:
        t('Specialists are ready-made subagents with a short prompt and skills. Instead of a generic subagent the mod substitutes a suitable specialist; if there is none, it can create a new one.'),
      fields: [
        {
          path: 'agents.enabled',
          label: t('Replace generic subagents with specialists'),
          kind: 'bool',
          help: t('Launching a subagent from the list below is replaced with a suitable specialist from the registry (“Agents”).'),
        },
        {
          path: 'agents.autoCreate',
          label: t('Create a specialist if none fits'),
          kind: 'bool',
          help: t('When no specialist fits, the author model (see below) writes a new one: one extra model call. When off, only the specialists you created by hand are used.'),
        },
        {
          path: 'agents.remapFrom',
          label: t('Which subagent types to replace'),
          kind: 'list',
          placeholder: 'general-purpose',
          mono: true,
          help: t('Subagent types separated by commas (for example general-purpose, Explore). Other types are launched as they are.'),
        },
        {
          path: 'agents.matchAt',
          label: t('Threshold for picking an existing specialist'),
          ...prob,
          help: t('The probability from Jev that a specialist fits the task. A lower threshold means an existing specialist is taken more often, but inexact matches are possible; a higher one means a new one is created more often.'),
        },
        {
          path: 'agents.maxAgents',
          label: t('Maximum specialists'),
          kind: 'number',
          step: 1,
          min: 0,
          max: 500,
          help: t('Auto-creation stops at this number of specialists. 0 means do not create automatically.'),
        },
        {
          path: 'agents.exposeToModel',
          label: t('Show specialists to Claude'),
          kind: 'bool',
          help: t('Adds the list of specialists to the subagent types available to Claude. This uses context, so it is hidden by default: the mod picks the specialist itself.'),
        },
        {
          path: 'agents.draftModel',
          label: t('Specialist author model'),
          kind: 'text',
          mono: true,
          help: t('The model that writes drafts of agents and skills. Sonnet 5.5 with low effort is usually enough.'),
        },
        {
          path: 'agents.draftTimeoutMs',
          label: t('Draft timeout'),
          kind: 'number',
          step: 1000,
          min: 5000,
          max: 120_000,
          unit: t('ms'),
          help: t('How long to wait for a specialist draft. After that the launch goes ahead as an ordinary subagent.'),
        },
        {
          path: 'agents.waitHint',
          label: t('Short waits in subagents'),
          kind: 'bool',
          help: t('Asks each subagent to wait for a build or process for no more than 4 minutes per call. The subagent cache lives for 5 minutes; after a long pause its whole context is written again (on the night of 5 October this cost ≈ $34 over 25 rebuilds).'),
        },
      ],
    },
    {
      id: 'compaction',
      title: t('Context compaction'),
      intro:
        t('Instead of a long summary the mod asks Jev to find stale tool calls and remove them from the context. This is cheaper and keeps the details.'),
      fields: [
        {
          path: 'compaction.enabled',
          label: t('Compact through Jev'),
          kind: 'bool',
          help: t('When off, the built-in compaction of Claude Code (summary) is always used.'),
        },
        {
          path: 'compaction.compactAtTokens',
          label: t('Compact at context size'),
          kind: 'number',
          step: 10000,
          min: 0,
          max: 2_000_000,
          unit: t('tokens'),
          help: t('The main threshold: when the context grows to this size, the mod compacts it through Jev. 200k is almost as good as 120–180k, but with fewer compactions; 600k (60% of the window) is almost useless. 0 means off.'),
        },
        {
          path: 'compaction.autoWindowTokens',
          label: t('Compact mid-turn and in subagents at'),
          kind: 'number',
          step: 10000,
          min: 0,
          max: 2_000_000,
          unit: t('tokens'),
          help: t('The mod can compact only between turns. At this size Claude Code compacts by itself, also in the middle of a long turn and inside subagents, and the mod prunes it through Jev. Set as Claude Code’s auto-compaction window (CLAUDE_CODE_AUTO_COMPACT_WINDOW) for each session; a value you set in the environment yourself wins. Keep it above the threshold above. 0 means Claude Code’s own window.'),
        },
        {
          path: 'compaction.thresholdMinReduction',
          label: t('Compact at the threshold only if Jev removes at least'),
          ...prob,
          help: t('Rewriting the cache after compaction pays off faster the more is removed: at 50% in about 40 steps, at 30% in 90+. If Jev can remove less than this share, threshold compaction is skipped (without the expensive built-in summary).'),
        },
        {
          path: 'compaction.recompactAfterTokens',
          label: t('Compact again no sooner than after'),
          kind: 'number',
          step: 10000,
          min: 0,
          max: 2_000_000,
          unit: t('tokens of growth'),
          help: t('After a compaction (or a skipped attempt) the next one happens only when the context grows by this much. Protects against compacting every turn.'),
        },
        {
          path: 'compaction.compactAtPercent',
          label: t('Request compaction at fill level'),
          kind: 'number',
          step: 5,
          min: 0,
          max: 95,
          unit: '%',
          help: t('An additional threshold as a percentage of the window (with a 1M window this is late). 0 means off, the token threshold is enough.'),
        },
        {
          path: 'compaction.minReductionRatio',
          label: t('Minimum savings'),
          ...prob,
          help: t('When Claude Code itself starts compaction (it hit the window or you typed /compact): if Jev removes less than this share, the built-in Claude Code summary is used.'),
        },
        {
          path: 'compaction.keepThreshold',
          label: t('Keep threshold'),
          ...prob,
          help: t('A call or result whose importance, as estimated by Jev, is above the threshold is left untouched. A higher threshold keeps more and saves less.'),
        },
        {
          path: 'compaction.preserveRecentMessages',
          label: t('Leave the latest messages alone'),
          kind: 'number',
          step: 1,
          min: 0,
          max: 100,
          unit: t('msgs'),
          help: t('How many recent messages are never compacted. More is safer for the current work, with smaller savings.'),
        },
        {
          path: 'compaction.truncateHeadChars',
          label: t('Length of the kept beginning'),
          kind: 'number',
          step: 50,
          min: 0,
          max: 5000,
          unit: t('characters'),
          help: t('How many characters of the beginning of the output remain from a trimmed tool result.'),
        },
        {
          path: 'compaction.maxStateTokens',
          label: t('Maximum “state” for Jev'),
          kind: 'number',
          step: 1000,
          min: 2000,
          max: 30_000,
          unit: t('tokens'),
          help: t('How much history is shown to Jev for its estimate. More means more accurate decisions, but the request is more expensive and slower.'),
        },
        {
          path: 'compaction.maxRequestTokens',
          label: t('Maximum Jev request size'),
          kind: 'number',
          step: 1000,
          min: 3000,
          max: 31_000,
          unit: t('tokens'),
          help: t('The upper limit of a single request to Jev; a long history is split into several requests.'),
        },
        {
          path: 'compaction.onReturn',
          label: t('Compact when the cache expired during a pause'),
          kind: 'bool',
          help: t('When you do not write for longer than the cache lifetime (60 minutes on a subscription), the mod compacts the context through Jev by itself right after the cache expires, while you are away (and when such a session is opened after a restart). Rewriting the cache on your return is unavoidable, and this way it is smaller. When off, compaction happens only at the threshold or when Claude Code requests it.'),
        },
        {
          path: 'compaction.onReturnMinTokens',
          label: t('Compact on return from size'),
          kind: 'number',
          step: 5000,
          min: 0,
          max: 2_000_000,
          unit: t('tokens'),
          help: t('Compaction on return starts only if the context is at least this size. A smaller value means more compactions, but on a small context the gain is modest; a larger one means fewer, but only where rewriting the cache is really expensive.'),
        },
        {
          path: 'compaction.onReturnMinReduction',
          label: t('On return, compact if at least this much is removed'),
          ...prob,
          help: t('After the cache expires the rewrite is unavoidable, so any savings are free: the threshold is low. Below it nothing is done.'),
        },
        {
          path: 'compaction.fold',
          label: t('Fold old dialog text at compaction'),
          kind: 'bool',
          help: t('Compaction itself only prunes tool calls, so in a long chat earlier answers, agent reports, monitor events and long pastes were carried through every compaction and written into the cache again each time. With this on, each compaction folds such messages older than the newest turns to their first lines plus a link to a file with the full text; Claude reads the file when it needs a detail. Jev keeps the messages the current work still relies on. On a long real chat this removed 35–67% of the dialog text per compaction; graded in hindsight, none of 380 folded messages was needed beyond its first lines.'),
        },
        {
          path: 'compaction.foldKeepTurns',
          label: t('Never fold the newest turns'),
          kind: 'number',
          step: 1,
          min: 1,
          max: 50,
          unit: t('turns'),
          help: t('How many of your newest prompts, with everything after them, always stay verbatim.'),
        },
        {
          path: 'compaction.archive',
          label: t('Save removed content to an archive'),
          kind: 'bool',
          help: t('Every removed call (input and full output) is saved to a file, and a link to it stays in the context. If an old detail is needed, Claude reads it from the file instead of running it again. Archive reads appear in the journal as output-read. Kept for 7 days, with the same overall limit as trimmed outputs.'),
        },
        {
          path: 'compaction.maxPruneRatio',
          label: t('Limit on the share removed in one compaction'),
          ...prob,
          min: 0.5,
          help: t('If Jev wants to remove more than this share of the history, the mod restores the calls Jev was least sure about removing until the share drops to the limit; a huge output is restored only if it cannot be avoided. A single compaction that removed 95% (it happened on 5 October) leaves the model guessing what it had. 1 means no limit; below 0.5 is not allowed: such a compaction would not reach the minimum benefit and would be skipped.'),
        },
        {
          path: 'compaction.resultPreviewChars',
          label: t('Result preview for Jev, characters'),
          kind: 'number',
          step: 10,
          min: 0,
          max: 1000,
          unit: t('chars'),
          help: t('How many characters from the start, and as many from the end, of each tool output Jev sees when deciding whether to keep it. 0 means only the output size, as in the original library: then Jev decides almost blind. The preview takes part of the state budget; if there is not enough room, previews of old calls are dropped first.'),
        },
      ],
    },
    {
      id: 'handoff',
      title: t('Context handoff to a new chat'),
      intro:
        t('In the old chat, /jevg getctx [focus] builds a “capsule”: a brief from this chat’s model (while the cache is warm), requests and final answers by turn (recent ones in full, those Jev rates as needed in condensed form, the rest in one line), changed files and the latest checks. The prompt for the new chat is copied to the clipboard. Paste it into a new chat of this project and the capsule attaches itself. Without pasting, /jevg ctx works in the new chat. The new chat reads ~10–15k instead of hundreds of thousands of tokens of old history at every step. /jevg fresh [focus] does the same without a new window: it builds the capsule, clears the chat (/clear) and attaches the capsule to your next message.'),
      fields: [
        {
          path: 'handoff.enabled',
          label: t('Context handoff'),
          kind: 'bool',
          help: t('The /jevg fresh, /jevg getctx and /jevg ctx commands and automatic attaching of the capsule by the jev-ctx:… link in a new chat.'),
        },
        {
          path: 'handoff.maxTokens',
          label: t('Capsule size'),
          kind: 'number',
          step: 1000,
          min: 2000,
          max: 60_000,
          unit: t('tokens'),
          help: t('Capsule budget. It first holds the brief, the last two turns in full and the first turn (usually the task itself), the rest by relevance. More means fewer lost details, but every step of the new chat reads more.'),
        },
        {
          path: 'handoff.brief',
          label: t('Brief from the old chat model'),
          kind: 'select',
          options: [
            { value: 'auto', label: t('only while the cache is warm') },
            { value: 'always', label: t('always') },
            { value: 'never', label: t('never') },
          ],
          help: t('The brief: goal, state, decisions and why, rejected options, next step. It is one short turn of the old chat. While the cache is warm it is almost free (a cache read plus ~1.5k output tokens); on a cold cache it would cost rewriting the whole context. The --brief and --nobrief command flags override this setting.'),
        },
        {
          path: 'handoff.briefWords',
          label: t('Brief length'),
          kind: 'number',
          step: 50,
          min: 100,
          max: 1500,
          unit: t('words'),
          help: t('Upper limit of the brief length.'),
        },
        {
          path: 'handoff.useJev',
          label: t('Turn selection through Jev'),
          kind: 'bool',
          help: t('Jev judges which old turns are needed to continue the work (taking the focus into account). When off, old turns are taken by recency.'),
        },
        {
          path: 'handoff.suggestAtTokens',
          label: t('Suggest a new chat at context from'),
          kind: 'number',
          step: 10000,
          min: 0,
          max: 2_000_000,
          unit: t('tokens'),
          help: t('If Jev sees that the request starts a new task and the context is already at least this size, the mod suggests continuing with a clean chat via /jevg fresh. A suggestion only, at most once every 10 turns, works in shadow mode too. 0 means do not suggest.'),
        },
        {
          path: 'handoff.suggestAt',
          label: t('Jev confidence for the suggestion'),
          ...prob,
          help: t('The “new task” probability at which the suggestion is shown.'),
        },
        {
          path: 'handoff.suggestColdAtTokens',
          label: t('Suggest when the cache is cold from'),
          kind: 'number',
          step: 10_000,
          min: 0,
          max: 2_000_000,
          unit: t('tokens'),
          help: t('If you came back after a pause longer than the cache lifetime and the context is at least this size, the next turn will write all of it again. The mod will suggest /jevg fresh: continue in the same window with a clean chat and a capsule. Off by default (0): after a pause the mod first compacts the chat itself (“Compact when the cache expired during a pause”).'),
        },
        {
          path: 'handoff.keepDays',
          label: t('Keep capsules'),
          kind: 'number',
          step: 1,
          min: 1,
          max: 365,
          unit: t('days'),
          help: t('Capsules are stored in ~/.claude/jev-governor/handoffs/.'),
        },
      ],
    },
    {
      id: 'trim',
      title: t('Trimming large outputs'),
      intro:
        t('The mod trims long test, build or install output before it enters the chat: it keeps the summary line (tests passed or failed, how many), every error, warning and failure line with its neighboring lines, summary lines, the start and end of the output, and from the middle whatever Jev considers needed for the task. The full output is saved to a file, and Claude reads it from there instead of running the command again. This way thousands of log lines do not reach the context and the cache.'),
      fields: [
        {
          path: 'trim.enabled',
          label: t('Trim large outputs'),
          kind: 'bool',
          help: t('When off, tool results enter the chat in full. When on, context is saved, but Claude does not see outputs completely (the full text is available in the saved file).'),
        },
        {
          path: 'trim.minChars',
          label: t('Minimum size of test and build output'),
          kind: 'number',
          step: 1000,
          min: 1000,
          max: 1_000_000,
          unit: t('characters'),
          help: t('Test and build outputs shorter than this are left alone. A smaller value trims more and saves more, but details are lost more often; a larger one is safer, but long logs pass through in full.'),
        },
        {
          path: 'trim.hugeChars',
          label: t('Size above which any output is trimmed'),
          kind: 'number',
          step: 5000,
          min: 5000,
          max: 4_000_000,
          unit: t('characters'),
          help: t('Any other output (not tests or a build) longer than this is trimmed too. Smaller means more aggressive savings, but, for example, a large file or a search may arrive incomplete; larger means such outputs stay as they are. Claude Code itself replaces Bash outputs longer than ~30k with a preview, so for Bash this threshold almost never fires.'),
        },
        {
          path: 'trim.listChars',
          label: t('Long lists (ls, du, ps, find)'),
          kind: 'number',
          step: 1000,
          min: 0,
          max: 1_000_000,
          unit: t('characters'),
          help: t('A list of files or processes longer than this is cut to the first 40 and last 15 lines; the full list is in a file, and Claude finds what it needs with grep. 0 means do not shorten.'),
        },
        {
          path: 'trim.briefChars',
          label: t('Successful tests and builds: short trim from'),
          kind: 'number',
          step: 500,
          min: 0,
          max: 1_000_000,
          unit: t('characters'),
          help: t('A successful test, build or install run (npm test, cargo build, tsc…) longer than this but shorter than the test log limit keeps only the outcome, the summary, the warnings and the first and last lines; the full output is in a file. A run with any failure line, a failed run and a run Claude already filtered (| tail, | grep) stay whole. 0 means never.'),
        },
        {
          path: 'trim.logs',
          label: t('Logs of other commands (Jev decides)'),
          kind: 'select',
          options: [
            { value: 'shadow', label: t('Shadow (only record what Jev decides)') },
            { value: 'on', label: t('On') },
            { value: 'off', label: t('Off') },
          ],
          help: t('Output of other commands (a script, a server, a deploy, git push, a polling loop) longer than the limit below goes to Jev with one question: is this a log, where only the outcome, errors and key lines matter, or data Claude ran the command to get? Only a log is trimmed: its start and end, errors and warnings, lines with addresses and launch or finish status remain, repeats that differ only in numbers are counted. Reads (cat, sed, grep, git diff), inline scripts (python3 -c), outputs Claude filtered itself (| tail, | grep) and failed commands are never offered. In shadow mode Jev\'s verdict is only recorded.'),
        },
        {
          path: 'trim.logChars',
          label: t('Log check: from size'),
          kind: 'number',
          step: 500,
          min: 1000,
          max: 1_000_000,
          unit: t('characters'),
          help: t('Command outputs shorter than this are not offered to Jev as possible logs.'),
        },
        {
          path: 'trim.logAt',
          label: t('Log check: probability threshold'),
          ...prob,
          help: t('An output is trimmed as a log only if Jev\'s probability that it is a log is at least this. Measured on 7 October: real script and report outputs got at most 0.29, real logs (push, deploy, docker compose, dev server) 0.55–0.80. Higher means safer and rarer.'),
        },
        {
          path: 'trim.headLines',
          label: t('Lines from the start'),
          kind: 'number',
          step: 5,
          min: 0,
          max: 1000,
          unit: t('lines'),
          help: t('How many of the first lines of the output always stay: usually the command, versions and first messages. More gives a fuller beginning but smaller savings.'),
        },
        {
          path: 'trim.tailLines',
          label: t('Lines from the end'),
          kind: 'number',
          step: 10,
          min: 0,
          max: 2000,
          unit: t('lines'),
          help: t('How many of the last lines always stay: the summary, timing and exit code. More is safer, but the output will not get shorter.'),
        },
        {
          path: 'trim.contextLines',
          label: t('Lines around an error'),
          kind: 'number',
          step: 1,
          min: 0,
          max: 50,
          unit: t('lines'),
          help: t('How many lines before and after each error, warning or failure line stay next to it. More makes the cause clearer (trace, expected and actual), but the output is longer.'),
        },
        {
          path: 'trim.maxChars',
          label: t('Desired result size'),
          kind: 'number',
          step: 1000,
          min: 2000,
          max: 200_000,
          unit: t('characters'),
          help: t('A soft limit on the size of the text that is kept. Error and summary lines are not dropped for its sake, so the result may be longer. Smaller means more savings; larger means less chance of losing something needed.'),
        },
        {
          path: 'trim.useJev',
          label: t('Ask Jev what else is needed'),
          kind: 'bool',
          help: t('Jev looks at the skipped pieces of the middle of the output and returns those needed for the current task. This is one extra request to Jev per trim. When off, only errors, summaries, the start and the end remain.'),
        },
        {
          path: 'trim.jevKeepAt',
          label: t('Threshold for restoring a middle chunk'),
          ...prob,
          help: t('The lower it is, the more of the middle of the output Jev keeps: a chunk is restored if the probability that it is needed is not below the threshold. A lower threshold gives a fuller output and smaller savings; a higher one gives a shorter output, but a needed chunk may be lost.'),
        },
        {
          path: 'trim.keepDays',
          label: t('Keep full outputs'),
          kind: 'number',
          step: 1,
          min: 1,
          max: 90,
          unit: t('days'),
          help: t('How many days files with the full output stay in the outputs folder. Longer lets Claude reread an old output in a long session; shorter uses less disk space.'),
        },
        {
          path: 'trim.maxStorageMb',
          label: t('Storage limit for full outputs'),
          kind: 'number',
          step: 50,
          min: 10,
          max: 10000,
          unit: t('MB'),
          help: t('If all saved outputs together exceed this, the oldest sessions are deleted whole at session start. In addition, every start deletes files older than the retention period and empty folders.'),
        },
      ],
    },
    {
      id: 'savings',
      title: t('Savings calculation'),
      intro:
        t('How the “Savings” tab is calculated: dollar amounts at Anthropic list prices (API equivalent), subscription limits are used up in proportion to the same tokens. These settings affect only the calculation, not how the mod works.'),
      fields: [
        {
          path: 'savings.effortFactor',
          label: t('Share of output per effort level'),
          kind: 'number',
          step: 0.05,
          min: 0,
          max: 0.6,
          help: t('The share of a turn’s output saved by lowering effort by one level; about 0.3 according to the project’s A/B tests. Cache reads are not counted. Affects only the estimate.'),
        },
        {
          path: 'savings.defaultBaseModel',
          label: t('Model without the mod'),
          kind: 'select',
          options: [
            { value: 'claude-opus-5-5', label: 'Opus 5.5' },
            { value: 'claude-sonnet-5-5', label: 'Sonnet 5.5' },
          ],
          help: t('What the sessions would have run on without the mod. Needed for old journal entries where this is not recorded.'),
        },
        {
          path: 'savings.defaultBaseEffort',
          label: t('Effort without the mod'),
          kind: 'effort',
          help: t('The effort level the sessions would have run at without the mod; also only for old journal entries where this is not recorded.'),
        },
      ],
    },
    {
      id: 'jev',
      title: t('Jev and key'),
      fields: [
        {
          path: 'jev.model',
          label: t('Jev model'),
          kind: 'text',
          mono: true,
          help: t('Identifier of the Jev model for the System One API.'),
        },
        {
          path: 'jev.endpoint',
          label: t('API address'),
          kind: 'text',
          mono: true,
          help: t('TypeSafe-compatible System One address. OpenRouter by default. The key is sent to this address.'),
        },
        {
          path: 'jev.keyFile',
          label: t('Key file'),
          kind: 'text',
          mono: true,
          help: t('Where the OpenRouter key is stored (~ is the home folder). The OPENROUTER_API_KEY environment variable takes precedence over the file. Save the settings first, then the key.'),
        },
        {
          path: 'jev.timeoutMs',
          label: t('Decision timeout'),
          kind: 'number',
          step: 100,
          min: 300,
          max: 20_000,
          unit: t('ms'),
          help: t('If Jev takes longer to respond, the decision is dropped and nothing changes. Smaller means a faster turn, but “no decision” more often.'),
        },
      ],
    },
    {
      id: 'projects',
      title: t('Projects'),
      intro:
        t('Project pages (the “Projects” tab): commands found in the project files and commands that Claude ran successfully there. Project folders are only read, nothing is written to them.'),
      fields: [
        {
          path: 'projects.enabled',
          label: t('Project panel'),
          kind: 'bool',
          help: t('The “Projects” tab, remembering the commands Claude ran successfully, and command descriptions. Not related to saving limits; when off, the mod and the interface leave projects alone.'),
        },
        {
          path: 'projects.descriptionLanguage',
          label: t('Command description language'),
          kind: 'select',
          options: [
            { value: 'ru', label: 'Русский' },
            { value: 'en', label: 'English' },
          ],
          help: t('Descriptions are written by Claude Sonnet through an open session with the mod; when the language changes, they are rewritten at the next project refresh.'),
        },
        {
          path: 'projects.learnFromClaude',
          label: t('Remember commands run by Claude'),
          kind: 'bool',
          help: t('The mod records in the journal the commands Claude runs in a project (without output and without commands that look like secrets). Successful commands appear in the project list marked “Claude ×N”.'),
        },
        {
          path: 'projects.minSuccesses',
          label: t('Successful runs before showing'),
          kind: 'number',
          step: 1,
          min: 1,
          max: 50,
          help: t('A command that is not in the project files is shown after this many successful Claude runs in the last 30 days. More means fewer accidental commands in the list.'),
        },
        {
          path: 'projects.describeWithClaude',
          label: t('Describe commands with Claude'),
          kind: 'bool',
          help: t('On a project refresh a request is placed in the data folder, and an open Claude Code session with the mod answers it with Sonnet at low effort (usually within a minute). Without an open session there will be no descriptions: drafts from the project files are shown instead.'),
        },
        {
          path: 'projects.showWorktrees',
          label: t('Show worktrees'),
          kind: 'bool',
          help: t('Claude Code git worktrees (…/.claude/worktrees/…) in the project list. This can also be toggled in place on the “Projects” page.'),
        },
        {
          path: 'ui.terminal',
          label: t('Terminal'),
          kind: 'select',
          disabled: true,
          options: [{ value: 'Terminal', label: 'Terminal.app' }],
          help: t('Where the “Run in terminal” button opens. Other terminals later.'),
        },
      ],
    },
    {
      id: 'ui',
      title: t('Interface'),
      fields: [
        {
          path: 'ui.language',
          label: t('Interface language'),
          kind: 'select',
          options: [{ value: 'auto', label: t('Automatic') }, ...LANGS],
          help: t('Language of this page and of the mod\'s messages in chat. Automatic follows the language set in Claude Code, then the system language. It applies after saving. Command descriptions have their own language setting in the Projects section.'),
        },
        {
          path: 'ui.port',
          label: t('Settings port'),
          kind: 'number',
          step: 1,
          min: 1024,
          max: 65_535,
          help: t('The port of this interface (127.0.0.1 only). Applies after the server restarts.'),
        },
        {
          path: 'ui.showStatus',
          label: t('Show the decision in the status line'),
          kind: 'bool',
          help: t('The Claude Code status line shows the current model, effort and limit pressure.'),
        },
        {
          path: 'ui.nodePath',
          label: t('Path to Node'),
          kind: 'text',
          mono: true,
          help: t('Node for the /jevg ui command (looked up in PATH if just “node” is given). Version 23.6 or newer is required.'),
        },
      ],
    },
  ];
}

export type SettingsGroup = { id: string; title: string; description: string; sectionIds: string[] };

/** The tiles of the settings page, each opening a few of the sections above. */
export function getGroups(): SettingsGroup[] {
  return [
    {
      id: 'basics',
      title: t('Basics'),
      description: t('Interface language, the on/off switch, mode, and the Jev key and model.'),
      sectionIds: ['ui', 'general', 'jev'],
    },
    {
      id: 'models',
      title: t('Models & agents'),
      description: t('Which models and effort levels the mod picks for the main chat and subagents, and the specialist agents.'),
      sectionIds: ['models', 'main', 'subagents', 'agents'],
    },
    {
      id: 'context',
      title: t('Context'),
      description: t('Context compaction, handoff to a new chat, and trimming of large outputs.'),
      sectionIds: ['compaction', 'handoff', 'trim'],
    },
    {
      id: 'projects',
      title: t('Projects & savings'),
      description: t('The project panel with its commands, and how the savings are counted.'),
      sectionIds: ['projects', 'savings'],
    },
  ];
}
