// Moving work to a new chat: a compact "capsule" of the old one instead of
// its whole history (the idea: history is not context). A coding
// session's text is ~1.5% of its history and the rest is tool output, so the
// capsule is the person's requests and the assistant's final answers turn by
// turn (newest whole, older condensed, oldest one line each), the files it
// changed, the last test/build results and, when it was cheap to get, a brief
// the original chat's model wrote. Pure: the mod reads the session, asks Jev,
// writes the files.

import { callLabel } from './archive.ts';
import { estimateTokens } from './compaction/state.ts';
import type { JevQuestions } from './jev.ts';
import { detectOutcome } from './trim.ts';

export type CapsuleMessage = {
  role: 'user' | 'assistant';
  text: string;
  toolUses: readonly { tool_use_id?: string; tool: string; input: Record<string, unknown>; text?: string; isError?: boolean }[];
  toolResults?: readonly { tool_use_id: string; text: string; isError?: boolean }[];
};

export type Check = { command: string; outcome: string; failed: boolean; turn: number };

export type Turn = {
  /** 1-based, oldest first. */
  n: number;
  user: string;
  answer: string;
  calls: number;
  errors: number;
  /** Files the turn created or edited. */
  edited: string[];
};

export type Skeleton = {
  turns: Turn[];
  /** Claude Code's own compaction summary, when the history starts with one. */
  summary?: string;
  /** Changed files with their edit counts, most recent last. */
  files: { path: string; edits: number; lastTurn: number }[];
  /** The latest result of each test / build / check command, oldest first. */
  checks: Check[];
};

export type TurnPlan = 'full' | 'gist' | 'line';

/** Marks the prompt that asks the original chat for its brief (left out of the capsule). */
export const BRIEF_MARKER = '[jev-governor:getctx-brief]';

/** A capsule reference in a prompt: `jev-ctx:20261005-1912-a3f0`. */
export const CTX_REF = /\bjev-ctx:(\d{8}-\d{4}-[0-9a-f]{4})\b/;

const COMPACT_SUMMARY = /^This session is being continued from a previous conversation/;
/** A skill's body the engine inserts as a user message: not something the person typed. */
const SKILL_BODY = /^Base directory for this skill:/;

const EDIT_TOOLS = new Set(['Edit', 'Write', 'MultiEdit', 'NotebookEdit']);

const CHECK_COMMAND =
  /\b(test|tests|vitest|jest|pytest|nextest|playwright|cypress|tsc|typecheck|vue-tsc|lint|eslint|clippy|build|check|compile|make)\b/;
/** Scripts and file edits that merely mention a test word. */
const NOT_A_CHECK = /^\s*(cat|echo|printf|python3?\s+-|node\s+-e|sed|awk|grep|rg|git|ls|find|head|tail)\b/;

/** Drops what the engine wraps around a prompt (reminders, command echoes, notifications). */
export function cleanText(text: string): string {
  return text
    .replace(/<(system-reminder|command-message|command-name|command-args|local-command-stdout|local-command-stderr|local-command-caveat|task-notification|user-prompt-submit-hook)[^>]*>[\s\S]*?<\/\1>/g, ' ')
    .replace(/<\/?pasted_content[^>]*>/g, '')
    .replace(/^Caveat: The messages below were generated by the user while running local commands.*$/gm, '')
    .replace(/\n{3,}/g, '\n\n')
    .trim();
}

/** Head and tail of a long text, cut at whole lines where it can. */
export function excerpt(text: string, max: number): string {
  const flat = text.trim();
  if (flat.length <= max) return flat;
  const head = Math.round(max * 0.7);
  const tail = max - head;
  return `${flat.slice(0, head).trimEnd()}\n[…]\n${flat.slice(-tail).trimStart()}`;
}

function oneLine(text: string, max: number): string {
  const flat = text.replace(/\s+/g, ' ').trim();
  return flat.length > max ? `${flat.slice(0, max)}…` : flat;
}

function editedPath(input: Record<string, unknown>): string | undefined {
  const path = input.file_path ?? input.notebook_path ?? input.path;
  return typeof path === 'string' ? path : undefined;
}

/**
 * Splits the conversation into turns (a turn opens with a prompt the person
 * typed) and collects what the capsule needs from each. Our own brief prompt
 * and its answer are left out: the brief travels on its own.
 */
export function buildSkeleton(messages: readonly CapsuleMessage[], cwd = ''): Skeleton {
  const relative = (path: string): string => (cwd && path.startsWith(`${cwd}/`) ? path.slice(cwd.length + 1) : path);
  const results = new Map<string, { text: string; isError: boolean }>();
  for (const message of messages) {
    for (const result of message.toolResults ?? []) {
      results.set(result.tool_use_id, { text: result.text, isError: result.isError ?? false });
    }
  }
  const turns: Turn[] = [];
  const files = new Map<string, { path: string; edits: number; lastTurn: number }>();
  const checks = new Map<string, Check>();
  let summary: string | undefined;
  let current: Turn | undefined;
  let skipping = false;
  for (const message of messages) {
    if (message.role === 'user') {
      const text = cleanText(message.text);
      if (!text) continue;
      if (SKILL_BODY.test(text)) continue;
      if (COMPACT_SUMMARY.test(text)) {
        summary = text;
        current = undefined;
        continue;
      }
      if ((message.toolResults?.length ?? 0) > 0 && current) continue;
      skipping = text.includes(BRIEF_MARKER);
      if (skipping) {
        current = undefined;
        continue;
      }
      current = { n: turns.length + 1, user: text, answer: '', calls: 0, errors: 0, edited: [] };
      turns.push(current);
      continue;
    }
    if (skipping || !current) continue;
    const text = cleanText(message.text);
    if (text) current.answer = text;
    for (const tool of message.toolUses) {
      current.calls++;
      const result = tool.tool_use_id ? results.get(tool.tool_use_id) : undefined;
      const isError = tool.isError ?? result?.isError ?? false;
      if (isError) current.errors++;
      if (EDIT_TOOLS.has(tool.tool) && !isError) {
        const found = editedPath(tool.input);
        const path = found === undefined ? undefined : relative(found);
        if (path) {
          if (!current.edited.includes(path)) current.edited.push(path);
          const file = files.get(path) ?? { path, edits: 0, lastTurn: 0 };
          file.edits++;
          file.lastTurn = current.n;
          files.delete(path);
          files.set(path, file);
        }
      }
      const command = tool.tool === 'Bash' && typeof tool.input.command === 'string' ? tool.input.command : undefined;
      // The command proper: its first line without a leading `cd …`, up to the first pipe or separator.
      const first = (command?.split('\n')[0] ?? '').trim().replace(/^cd\s+\S+\s*&&\s*/, '');
      const head = first.split(/\s*(?:\||;|&&|\|\|)\s*/)[0] ?? '';
      if (head && CHECK_COMMAND.test(head) && !NOT_A_CHECK.test(head)) {
        const output = result?.text ?? tool.text ?? '';
        const outcome = detectOutcome(output.split('\n'), isError);
        // Without a test summary or an error there is nothing to report.
        if (outcome.status !== 'unknown' && !/\(0 passed, 0 failed/.test(outcome.detail)) {
          const key = oneLine(first, 160);
          checks.delete(key);
          checks.set(key, { command: key, outcome: outcome.detail, failed: outcome.status !== 'passed', turn: current.n });
        }
      }
    }
  }
  return { turns, summary, files: [...files.values()], checks: [...checks.values()] };
}

const SIZE = {
  full: { user: 2_500, answer: 4_000 },
  gist: { user: 400, answer: 600 },
  line: { user: 140, answer: 160 },
};

/** Quoted text must not open sections of its own: its headings become bold lines. */
function quoted(text: string): string {
  return text.replace(/^#{1,6}\s+(.+)$/gm, '**$1**');
}

export function renderTurn(turn: Turn, plan: TurnPlan): string {
  if (plan === 'line') {
    const answer = turn.answer ? ` → ${oneLine(turn.answer, SIZE.line.answer)}` : '';
    return `- Turn ${turn.n}: ${oneLine(turn.user, SIZE.line.user)}${answer}`;
  }
  const size = SIZE[plan];
  const tools = [
    turn.calls > 0 ? `${turn.calls} tool call(s)${turn.errors > 0 ? `, ${turn.errors} failed` : ''}` : '',
    turn.edited.length > 0 ? `changed ${turn.edited.slice(0, 8).map((p) => p.split('/').pop()).join(', ')}${turn.edited.length > 8 ? '…' : ''}` : '',
  ].filter(Boolean);
  return [
    `### Turn ${turn.n}${plan === 'gist' ? ' (condensed)' : ''}`,
    `**User:** ${quoted(excerpt(turn.user, size.user))}`,
    turn.answer ? `**Assistant:** ${quoted(excerpt(turn.answer, size.answer))}` : '**Assistant:** (no final text)',
    tools.length > 0 ? `_${tools.join('; ')}_` : '',
  ]
    .filter(Boolean)
    .join('\n\n');
}

/**
 * How much of each turn goes in, within `budget` tokens. The newest two go in
 * full and the first (usually the task itself) at least condensed; the rest
 * by Jev's `need` (≥ 0.7 full, < 0.3 one line) or, without it, the next four
 * condensed and older ones one line. Over budget, the least needed turns
 * (without Jev: the oldest) are reduced first, then left out (the transcript
 * keeps them); the first and newest two go last.
 */
export function planTurns(turns: readonly Turn[], budget: number, need?: ReadonlyMap<number, number>): Map<number, TurnPlan | 'omit'> {
  const plans = new Map<number, TurnPlan | 'omit'>();
  const newest = turns.length;
  const recent = (turn: Turn): boolean => newest - turn.n < 2;
  for (const turn of turns) {
    const age = newest - turn.n;
    const p = need?.get(turn.n);
    let plan: TurnPlan;
    if (recent(turn)) plan = 'full';
    else if (p !== undefined) plan = p >= 0.7 ? 'full' : p >= 0.3 ? 'gist' : 'line';
    else plan = age < 6 ? 'gist' : 'line';
    if (turn.n === 1 && plan === 'line') plan = 'gist';
    plans.set(turn.n, plan);
  }
  const cost = (turn: Turn): number => {
    const plan = plans.get(turn.n)!;
    return plan === 'omit' ? 0 : estimateTokens(renderTurn(turn, plan));
  };
  let total = turns.reduce((sum, turn) => sum + cost(turn), 0);
  const lower = (turn: Turn, to: TurnPlan | 'omit'): void => {
    const before = cost(turn);
    plans.set(turn.n, to);
    total += cost(turn) - before;
  };
  // Least needed first; without Jev's answer a turn counts by its age.
  const value = (turn: Turn): number => need?.get(turn.n) ?? turn.n / (newest + 1);
  const middle = turns.filter((t) => !recent(t) && t.n !== 1).sort((a, b) => value(a) - value(b) || a.n - b.n);
  const order: readonly (TurnPlan | 'omit')[] = ['full', 'gist', 'line', 'omit'];
  for (let step = 0; step < 3; step++) {
    for (const turn of middle) {
      if (total <= budget) return plans;
      if (plans.get(turn.n) === order[step]) lower(turn, order[step + 1]!);
    }
  }
  // Still too long: the first turn, then the newest two, condensed.
  for (const turn of [...turns.filter((t) => t.n === 1 && !recent(t)), ...turns.filter(recent)]) {
    if (total > budget && plans.get(turn.n) === 'full') lower(turn, 'gist');
  }
  for (const turn of turns.filter((t) => t.n === 1 && !recent(t))) {
    if (total > budget && plans.get(turn.n) === 'gist') lower(turn, 'line');
  }
  return plans;
}

export const HANDOFF_STATE_CONTEXT =
  'A Claude Code coding chat is being continued in a new chat that will not see it. The new chat gets the newest turns in full; for each older turn decide whether it must come along. `turns` lists them (the person\'s request, the assistant\'s final answer), oldest first.';

/** Older turns Jev is asked about (the newest two always go in full). */
export function candidateTurns(turns: readonly Turn[], max = 60): Turn[] {
  return turns.slice(0, Math.max(0, turns.length - 2)).slice(-max);
}

export function turnState(turns: readonly Turn[], candidates: readonly Turn[], focus: string): object {
  return {
    context: HANDOFF_STATE_CONTEXT,
    focus: focus || 'continue the most recent work',
    newest_turns: turns.slice(-2).map((t) => ({ turn: t.n, user: oneLine(t.user, 600), answer: oneLine(t.answer, 600) })),
    turns: candidates.map((t) => ({ turn: t.n, user: oneLine(t.user, 300), answer: oneLine(t.answer, 300) })),
  };
}

export function turnQuestions(candidates: readonly Turn[]): JevQuestions {
  return Object.fromEntries(
    candidates.map((t) => [
      `need_t${t.n}`,
      {
        type: 'noul' as const,
        instructions: `Turn ${t.n} holds something the assistant needs to continue the work toward focus in the new chat (a decision, constraint, result, open problem or the person's preference) that the newest turns do not already carry`,
      },
    ]),
  );
}

export type CapsuleMeta = {
  id: string;
  project: string;
  cwd: string;
  session: string;
  createdAt: string;
  focus: string;
  /** Claude Code's transcript of the old chat, when it was found. */
  transcript?: string;
  /** Archive of pruned tool outputs, when the old chat has one. */
  archive?: string;
};

export function renderCapsule(input: {
  meta: CapsuleMeta;
  skeleton: Skeleton;
  plans: ReadonlyMap<number, TurnPlan | 'omit'>;
  brief?: string;
}): { text: string; tokens: number } {
  const { meta, skeleton, plans, brief } = input;
  const where = [
    meta.transcript ? `full transcript of the previous chat: ${meta.transcript}` : '',
    meta.archive ? `pruned tool outputs: ${meta.archive}` : '',
  ].filter(Boolean);
  const omitted = skeleton.turns.filter((t) => plans.get(t.n) === 'omit').length;
  const parts: string[] = [
    `# Context from a previous chat — ${meta.project}`,
    `jev-ctx:${meta.id} · ${meta.createdAt.slice(0, 16).replace('T', ' ')} · session ${meta.session} · ${skeleton.turns.length} turn(s)`,
    [
      'This is a handoff from an earlier Claude Code chat in this project; that chat is not visible here. Continue the work from it. Files on disk are current, so re-read a file before editing it rather than trusting a quote below.',
      where.length > 0 ? `Details left out here: ${where.join('; ')} — read only what you need.` : '',
      meta.focus ? `Focus: ${meta.focus}` : '',
    ]
      .filter(Boolean)
      .join('\n'),
  ];
  if (brief?.trim()) parts.push(`## Brief from the previous chat\n\n${brief.trim()}`);
  if (skeleton.summary) parts.push(`## Earlier summary (Claude Code compaction)\n\n${excerpt(skeleton.summary, 6_000)}`);
  const lines: string[] = [];
  if (omitted > 0) lines.push(`_${omitted} turn(s) judged least needed are left out (see the transcript)._`);
  let block: string[] = [];
  const flush = (): void => {
    if (block.length > 0) lines.push(block.join('\n'));
    block = [];
  };
  for (const turn of skeleton.turns) {
    const plan = plans.get(turn.n) ?? 'line';
    if (plan === 'omit') continue;
    if (plan === 'line') {
      block.push(renderTurn(turn, plan));
      continue;
    }
    flush();
    lines.push(renderTurn(turn, plan));
  }
  flush();
  if (lines.length > 0) parts.push(`## Conversation, oldest first\n\n${lines.join('\n\n')}`);
  if (skeleton.files.length > 0) {
    const files = skeleton.files.slice(-40).map((f) => `- ${f.path} (${f.edits} edit${f.edits === 1 ? '' : 's'}, last in turn ${f.lastTurn})`);
    parts.push(`## Files changed\n\n${files.join('\n')}`);
  }
  if (skeleton.checks.length > 0) {
    const checks = skeleton.checks.slice(-8).map((c) => `- \`${oneLine(c.command, 160)}\` (turn ${c.turn}) → ${c.outcome}`);
    parts.push(`## Last checks\n\n${checks.join('\n')}`);
  }
  const text = `${parts.join('\n\n')}\n`;
  return { text, tokens: Math.round(estimateTokens(text)) };
}

/** The sentence the new chat's model follows when the mod did not attach the capsule. */
export const FALLBACK_HINT = 'если он не подключён к этому сообщению, сначала прочитай этот файл';
const FALLBACK_HINT_EN = 'if it is not attached to this message, read this file first';

/** What the person pastes into the new chat. */
export function pastePrompt(meta: Pick<CapsuleMeta, 'id' | 'focus'>, path: string, title: string, lang: 'ru' | 'en' = 'ru'): string {
  if (lang === 'en') {
    return [
      `jev-ctx:${meta.id} — continuing work from the previous chat «${title}».`,
      `Previous chat context: ${path} (${FALLBACK_HINT_EN}).`,
      meta.focus ? `Task: ${meta.focus}` : '',
    ]
      .filter(Boolean)
      .join('\n');
  }
  return [
    `jev-ctx:${meta.id} — продолжаем работу из прошлого чата «${title}».`,
    `Контекст прошлого чата: ${path} (${FALLBACK_HINT}).`,
    meta.focus ? `Задача: ${meta.focus}` : '',
  ]
    .filter(Boolean)
    .join('\n');
}

/** The pasted prompt once the mod attached the capsule: no instruction to read the file. */
export function attachedPrompt(text: string): string {
  return text
    .replace(/Контекст прошлого чата: \S+ \([^)]*\)\./, 'Контекст прошлого чата подключён к этому сообщению.')
    .replace(/Previous chat context: \S+ \([^)]*\)\./, 'Previous chat context is attached to this message.');
}

export function briefPrompt(focus: string, words: number): string {
  return [
    `${BRIEF_MARKER} The person is moving this work to a fresh chat (/jevg getctx or /jevg fresh).`,
    `Write a handoff brief for the assistant who will continue there. It will not see this chat: only your brief and an abridged list of the person's requests and your final answers.`,
    `At most ${words} words, Markdown, in the language the person writes in, with these sections: Goal; State (done and verified vs. done but not verified); Decisions (each with its reason, including approaches tried and rejected); Next step and open questions; Key files and commands; Gotchas.`,
    focus ? `Keep what matters for: ${focus}.` : '',
    'Facts only. Do not call any tools and do not change anything; reply with the brief alone.',
  ]
    .filter(Boolean)
    .join(' ');
}

/** `20261005-1912-a3f0`: sortable, short enough to type. */
export function capsuleId(now: Date, random: number): string {
  const p = (n: number): string => String(n).padStart(2, '0');
  const hex = Math.floor(random * 0x10000)
    .toString(16)
    .padStart(4, '0');
  return `${now.getFullYear()}${p(now.getMonth() + 1)}${p(now.getDate())}-${p(now.getHours())}${p(now.getMinutes())}-${hex}`;
}

/** Claude Code's folder name for a project: every non-alphanumeric character as `-`. */
export function projectSlug(cwd: string): string {
  return cwd.replace(/[^A-Za-z0-9]/g, '-');
}

/** `/jevg getctx --brief focus words` → flags and focus. */
export function parseGetctxArgs(args: string): { brief?: boolean; focus: string } {
  let brief: boolean | undefined;
  const words: string[] = [];
  for (const word of args.trim().split(/\s+/).filter(Boolean)) {
    if (word === '--brief') brief = true;
    else if (word === '--nobrief' || word === '--no-brief') brief = false;
    else words.push(word);
  }
  return { brief, focus: words.join(' ') };
}
